/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypePrettyName  SWIG_Python_TypePrettyName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(const char *)     SWIG_TypePrettyName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *swig_type_list_handle;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *swig_type_list_handle;
  *swig_type_list_handle = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Return the pretty name associated with this type,
   that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME(const char *)
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/* 
   Compare two type names skipping the space characters, therefore
   "char*" == "char *" and "Class<int>" == "Class<int >", etc.

   Return 0 when the two name types are equivalent, as in
   strncmp, but skipping ' '.
*/
static int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
static int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}
  

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = *swig_type_list_handle;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * pyrun.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)
 
/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

typedef double (*py_objasdbl_conv)(PyObject *obj);

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);


#else


/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,                                  /* Number of items in variable part (ob_size) */
  (char *)"swigvarlink",              /* Type name (tp_name) */
  sizeof(swig_varlinkobject),         /* Basic size (tp_basicsize) */
  0,                                  /* Itemsize (tp_itemsize) */
  0,                                  /* Deallocator (tp_dealloc) */ 
  (printfunc) swig_varlink_print,     /* Print (tp_print) */
  (getattrfunc) swig_varlink_getattr, /* get attr (tp_getattr) */
  (setattrfunc) swig_varlink_setattr, /* Set attr (tp_setattr) */
  0,                                  /* tp_compare */
  (reprfunc) swig_varlink_repr,       /* tp_repr */
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_sequence */
  0,                                  /* tp_as_mapping */
  0,                                  /* tp_hash */
  0,                                  /* tp_call */
  0,                                  /* tp_str */
  0,                                  /* tp_getattro */
  0,                                  /* tp_setattro */
  0,                                  /* tp_as_buffer */
  0,                                  /* tp_flags */
  0,                                  /* tp_doc */
  0,                                  /* tp_traverse */
  0,                                  /* tp_clear */
  0,                                  /* tp_richcompare */
  0,                                  /* tp_weaklistoffset */
#if PY_VERSION_HEX >= 0x02020000
  0,                                  /* tp_iter */
  0,                                  /* tp_iternext */
  0,                                  /* tp_methods */
  0,                                  /* tp_members */
  0,                                  /* tp_getset */
  0,                                  /* tp_base */
  0,                                  /* tp_dict */
  0,                                  /* tp_descr_get */
  0,                                  /* tp_descr_set */
  0,                                  /* tp_dictoffset */
  0,                                  /* tp_init */
  0,                                  /* tp_alloc */
  0,                                  /* tp_new */
  0,                                  /* tp_free */
  0,                                  /* tp_is_gc */
  0,                                  /* tp_bases */
  0,                                  /* tp_mro */
  0,                                  /* tp_cache */
  0,                                  /* tp_subclasses */
  0,                                  /* tp_weaklist */
#endif
#if PY_VERSION_HEX >= 0x02030200
  0,                                  /* tp_del */
#endif
#ifdef COUNT_ALLOCS
  /* these must be last */
  0,                                  /* tp_alloc */
  0,                                  /* tp_free */
  0,                                  /* tp_maxalloc */
  0,                                  /*  tp_next */
#endif
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AS_STRING(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject_SetAttrString(pyobj,(char*)"thisown",Py_False);
  }
  return 0;

type_error:
  PyErr_Clear();
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      PyErr_Format(PyExc_TypeError, 
		   "Type error. Got %s, expected %s",
		   c, ty->name);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AS_STRING(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      PyErr_Format(PyExc_TypeError, 
		   "Type error. Got %s, expected %s",
		   c, ty->name);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject_SetAttrString(inst,(char*)"thisown",Py_True);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      if (constants[i].pvalue) {
	obj = PyString_FromString((char *) constants[i].pvalue);
      } else {
	Py_INCREF(Py_None);
	obj = Py_None;
      }
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_unsigned_char swig_types[0] 
#define  SWIGTYPE_p_char swig_types[1] 
#define  SWIGTYPE_p_KadCtag_iter swig_types[2] 
#define  SWIGTYPE_p_int128 swig_types[3] 
#define  SWIGTYPE_p_KadCcontext swig_types[4] 
#define  SWIGTYPE_p_void swig_types[5] 
#define  SWIGTYPE_p_KadC_version_t swig_types[6] 
static swig_type_info *swig_types[8];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _KadCmodule.so
  ------------------------------------------------*/
#define SWIG_init    init_KadCmodule

#define SWIG_name    "_KadCmodule"

/* Auxiliar swig  macros that appear in the header */

#define SWIG_OLDOBJ  1
#define SWIG_NEWOBJ  SWIG_OLDOBJ + 1
#define SWIG_PYSTR   SWIG_NEWOBJ + 1

#ifdef __cplusplus
#define SWIGSTATICINLINE(a) static inline a
#define SWIGSTATIC(a) static a
#define swig_new_array(size,Type) (new Type[(size)])
#define swig_delete(cptr) delete cptr
#define swig_delete_array(cptr) delete[] cptr
#define swig_const_cast(a,Type) const_cast<Type >(a)
#define swig_static_cast(a,Type) static_cast<Type >(a)
#define swig_reinterpret_cast(a,Type) reinterpret_cast<Type >(a)
#define swig_new_copy(ptr,Type) (new Type(*ptr))
#define swig_numeric_cast(a,Type) static_cast<Type >(a)

#else /* C case */

#define SWIGSTATICINLINE(a) static a
#define SWIGSTATIC(a) static a
#define swig_new_array(size,Type) ((Type*) malloc((size)*sizeof(Type)))
#define swig_delete(cptr) free((char*)cptr)
#define swig_delete_array(cptr) free((char*)cptr)
#define swig_const_cast(a,Type) (Type)(a)
#define swig_static_cast(a,Type) (Type)(a)
#define swig_reinterpret_cast(a,Type) (Type)(a)
#define swig_numeric_cast(a,Type) (Type)(a)
#define swig_new_copy(ptr,Type)  ((Type*)memcpy(malloc(sizeof(Type)),ptr,sizeof(Type)))

#endif /* __cplusplus */


/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_signed_SS_char PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_unsigned_SS_char PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_short PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_unsigned_SS_short PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_int PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_long PyInt_FromLong
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_float PyFloat_FromDouble
/*@@*/
/*@C:\\CYGWIN\\USR\\LOCAL\\BIN\\Lib\\python\\pymacros.swg,63,SWIG_define@*/
#define SWIG_From_double PyFloat_FromDouble
/*@@*/


#include <limits.h>


SWIGSTATICINLINE(int)
  SWIG_CheckLongInRange(long value, long min_value, long max_value,
			const char *errmsg)
{
  if (value < min_value) {
    if (errmsg) {
      PyErr_Format(PyExc_OverflowError, 
		   "value %ld is less than '%s' minimum %ld", 
		   value, errmsg, min_value);
    }
    return 0;    
  } else if (value > max_value) {
    if (errmsg) {
      PyErr_Format(PyExc_OverflowError,
		   "value %ld is greater than '%s' maximum %ld", 
		   value, errmsg, max_value);
    }
    return 0;
  }
  return 1;
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_long(PyObject * obj, long* val)
{
  if (PyInt_Check(obj)) {
    if (val) *val = PyInt_AS_LONG(obj);
    return 1;
  }
  if (PyLong_Check(obj)) {
    long v = PyLong_AsLong(obj);
    if (!PyErr_Occurred()) {
      if (val) *val = v;
      return 1;
    } else {
      if (!val) PyErr_Clear();
      return 0;
    }
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "a long is expected");
  }
  return 0;
 }


#if INT_MAX != LONG_MAX
SWIGSTATICINLINE(int)
  SWIG_AsVal_int(PyObject *obj, int *val)
{ 
  const char* errmsg = val ? "int" : 0;
  long v;
  if (SWIG_AsVal_long(obj, &v)) {
    if (SWIG_CheckLongInRange(v, INT_MIN,INT_MAX, errmsg)) {
      if (val) *val = swig_numeric_cast(v, int);
      return 1;
    } else {
      return 0;
    }
  } else {
    PyErr_Clear();
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "an int is expected");
  }
  return 0;    
}
#else
SWIGSTATICINLINE(int)
  SWIG_AsVal_int(PyObject *obj, int *val)
{
  return SWIG_AsVal_long(obj,(long*)val);
}
#endif


SWIGSTATICINLINE(int)
SWIG_As_int(PyObject* obj)
{
  int v;
  if (!SWIG_AsVal_int(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(int));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_int(PyObject* obj)
{
  return SWIG_AsVal_int(obj, (int*)0);
}


/* returns SWIG_OLDOBJ if the input is a raw char*, SWIG_PYSTR if is a PyString */
SWIGSTATIC(int)
SWIG_AsCharPtrAndSize(PyObject *obj, char** cptr, size_t* psize)
{
  static swig_type_info* pchar_info = 0;
  char* vptr = 0;
  if (!pchar_info) pchar_info = SWIG_TypeQuery("char *");
  if (SWIG_ConvertPtr(obj, (void**)&vptr, pchar_info, 0) != -1) {
    if (cptr) *cptr = vptr;
    if (psize) *psize = vptr ? (strlen(vptr) + 1) : 0;
    return SWIG_OLDOBJ;
  } else {
    if (PyString_Check(obj)) {
      if (cptr) {
	*cptr = PyString_AS_STRING(obj);
	if (psize) {
	  *psize = PyString_GET_SIZE(obj) + 1;
	}
      }
      return SWIG_PYSTR;
    }
  }
  if (cptr) {
    PyErr_SetString(PyExc_TypeError, "a string is expected");
  }
  return 0;
}


SWIGSTATICINLINE(int)
SWIG_AsCharPtr(PyObject *obj, char **val)
{
  char* cptr = 0;
  if (SWIG_AsCharPtrAndSize(obj, &cptr, (size_t*)(0))) {
    if (val) *val = cptr;
    return 1;
  }
  if (val) {
    PyErr_SetString(PyExc_TypeError, "a char* is expected");
  }
  return 0;
}


SWIGSTATICINLINE(PyObject *)
SWIG_FromCharPtr(const char* cptr)
{ 
  if (cptr) {
    size_t size = strlen(cptr);
    if (size > INT_MAX) {
      return SWIG_NewPointerObj(swig_const_cast(cptr,char*), 
				SWIG_TypeQuery("char *"), 0);
    } else {
      if (size != 0) {
	return PyString_FromStringAndSize(cptr, size);
      } else {
	return PyString_FromString(cptr);
      }
    }
  }
  Py_INCREF(Py_None);
  return Py_None;
}


SWIGSTATICINLINE(PyObject* )
  SWIG_From_unsigned_SS_long(unsigned long value)
{
  return (value > LONG_MAX) ?
    PyLong_FromUnsignedLong(value) 
    : PyInt_FromLong(swig_numeric_cast(value,long)); 
}


SWIGSTATICINLINE(int)
  SWIG_AsVal_unsigned_SS_long(PyObject * obj, unsigned long *val) 
{
  if (PyInt_Check(obj)) {
    long v = PyInt_AS_LONG(obj);
    if (v >= 0) {
      if (val) *val = v;
      return 1;
    }   
  }
  if (PyLong_Check(obj)) {
    unsigned long v = PyLong_AsUnsignedLong(obj);
    if (!PyErr_Occurred()) {
      if (val) *val = v;
      return 1;
    } else {
      if (!val) PyErr_Clear();
      return 0;
    }
  } 
  if (val) {
    PyErr_SetString(PyExc_TypeError, "an unsigned long is expected");
  }
  return 0;
}


SWIGSTATICINLINE(unsigned long)
SWIG_As_unsigned_SS_long(PyObject* obj)
{
  unsigned long v;
  if (!SWIG_AsVal_unsigned_SS_long(obj, &v)) {
    /*
      this is needed to make valgrind/purify happier.  the other
      solution is throw an exception, but since this code should work
      with plain C ....
     */
    memset((void*)&v, 0, sizeof(unsigned long));
  }
  return v;
}

  
SWIGSTATICINLINE(int)
SWIG_Check_unsigned_SS_long(PyObject* obj)
{
  return SWIG_AsVal_unsigned_SS_long(obj, (unsigned long*)0);
}


SWIGSTATIC(int)
SWIG_AsCharArray(PyObject *obj, char *val, size_t size)
{ 
  char* cptr; size_t csize;  
  if (SWIG_AsCharPtrAndSize(obj, &cptr, &csize)) {
    /* in C you can do:        

         char x[5] = "hello"; 

        ie, assing the array using an extra '0' char.
    */
    if ((csize == size + 1) && !(cptr[csize-1])) --csize;
    if (csize <= size) {
      if (val) {
	if (csize) memcpy(val, cptr, csize);
	if (csize < size) memset(val + csize, 0, size - csize);
      }
      return 1;
    }
  }
  if (val) {
    PyErr_Format(PyExc_TypeError, 
		 "a char array of maximum size %ld is expected", 
		 size);
  }
  return 0;
}


SWIGSTATICINLINE(PyObject *)
SWIG_FromCharArray(const char* carray, size_t size)
{
  if (size > INT_MAX) {
    SWIG_NewPointerObj(swig_const_cast(carray,char*), SWIG_TypeQuery("char *"), 0);
    return Py_None;    
  } else {
    return PyString_FromStringAndSize(carray, swig_numeric_cast(size,int));
  }
}

extern KadC_version_t const KadC_version;
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_KadCcontext_s_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_s_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->s = (KadC_status )arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_s_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_s_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->s);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_errmsg1_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_errmsg1_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    {
        if (arg1->errmsg1) free((char*)arg1->errmsg1);
        if (arg2) {
            arg1->errmsg1 = (char *) malloc(strlen(arg2)+1);
            strcpy((char*)arg1->errmsg1,arg2);
        } else {
            arg1->errmsg1 = 0;
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_errmsg1_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_errmsg1_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *) ((arg1)->errmsg1);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_errmsg2_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_errmsg2_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    {
        if (arg1->errmsg2) free((char*)arg1->errmsg2);
        if (arg2) {
            arg1->errmsg2 = (char *) malloc(strlen(arg2)+1);
            strcpy((char*)arg1->errmsg2,arg2);
        } else {
            arg1->errmsg2 = 0;
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_errmsg2_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_errmsg2_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *) ((arg1)->errmsg2);
    
    resultobj = SWIG_FromCharPtr(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pul_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_pul_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->pul = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pul_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_pul_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->pul);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pOKE_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_pOKE_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->pOKE = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pOKE_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_pOKE_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->pOKE);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pEKE_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_pEKE_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->pEKE = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pEKE_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_pEKE_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->pEKE);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pRKE_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_pRKE_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->pRKE = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_pRKE_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_pRKE_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->pRKE);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_inifilename_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_inifilename_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->inifilename = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_inifilename_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_inifilename_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->inifilename);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_inifile_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_inifile_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->inifile = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_inifile_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_inifile_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->inifile);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_wfile_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *arg2 = (void *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCcontext_wfile_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,&arg2,0,SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->wfile = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCcontext_wfile_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCcontext_wfile_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (void *) ((arg1)->wfile);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_KadCcontext(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_KadCcontext")) goto fail;
    result = (KadCcontext *)(KadCcontext *) calloc(1, sizeof(KadCcontext));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_KadCcontext, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_KadCcontext(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_KadCcontext",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * KadCcontext_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_KadCcontext, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_KadC_start(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    KadCcontext result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:KadC_start",&obj0,&obj1,&obj2)) goto fail;
    if (!SWIG_AsCharPtr(obj0, (char**)&arg1)) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    arg3 = (int)SWIG_As_int(obj2); 
    if (PyErr_Occurred()) SWIG_fail;
    result = KadC_start(arg1,arg2,arg3);
    
    {
        KadCcontext * resultptr;
        resultptr = (KadCcontext *) malloc(sizeof(KadCcontext));
        memmove(resultptr, &result, sizeof(KadCcontext));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_KadCcontext, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_init_network(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":KadC_init_network")) goto fail;
    result = (int)KadC_init_network();
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_stop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_stop",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadC_stop(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getnknodes(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getnknodes",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadC_getnknodes(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getncontacts(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getncontacts",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadC_getncontacts(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getfwstatus(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getfwstatus",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadC_getfwstatus(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getextIP(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    unsigned long result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getextIP",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned long)KadC_getextIP(arg1);
    
    resultobj = SWIG_From_unsigned_SS_long((unsigned long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getourhashID(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int128 result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getourhashID",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = KadC_getourhashID(arg1);
    
    {
        int128 * resultptr;
        resultptr = (int128 *) malloc(sizeof(int128));
        memmove(resultptr, &result, sizeof(int128));
        resultobj = SWIG_NewPointerObj((void *)(resultptr), SWIGTYPE_p_int128, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getourUDPport(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    unsigned short result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getourUDPport",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned short)KadC_getourUDPport(arg1);
    
    resultobj = SWIG_From_unsigned_SS_short((unsigned short)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_getourTCPport(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    unsigned short result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_getourTCPport",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned short)KadC_getourTCPport(arg1);
    
    resultobj = SWIG_From_unsigned_SS_short((unsigned short)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_nodesinbucket(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    int arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:nodesinbucket",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (int)nodesinbucket(arg1,arg2);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_republish(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    PyObject * obj5 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOOOO:KadC_republish",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj2, (char**)&arg3)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj3, (char**)&arg4)) SWIG_fail;
    arg5 = (int)SWIG_As_int(obj4); 
    if (PyErr_Occurred()) SWIG_fail;
    arg6 = (int)SWIG_As_int(obj5); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (int)KadC_republish(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5,arg6);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_find(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCcontext *arg1 = (KadCcontext *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int arg4 ;
    int arg5 ;
    int arg6 ;
    void *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    PyObject * obj5 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOOOO:KadC_find",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCcontext,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if (!SWIG_AsCharPtr(obj2, (char**)&arg3)) SWIG_fail;
    arg4 = (int)SWIG_As_int(obj3); 
    if (PyErr_Occurred()) SWIG_fail;
    arg5 = (int)SWIG_As_int(obj4); 
    if (PyErr_Occurred()) SWIG_fail;
    arg6 = (int)SWIG_As_int(obj5); 
    if (PyErr_Occurred()) SWIG_fail;
    result = (void *)KadC_find(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5,arg6);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagsleft_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned long arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_tagsleft_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (unsigned long)SWIG_As_unsigned_SS_long(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->tagsleft = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagsleft_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned long result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_tagsleft_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned long) ((arg1)->tagsleft);
    
    resultobj = SWIG_From_unsigned_SS_long((unsigned long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_pb_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_pb_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_unsigned_char,
    SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->pb = (unsigned char const *)arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_pb_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_pb_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char *) ((arg1)->pb);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_unsigned_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_bufend_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_bufend_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_unsigned_char,
    SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->bufend = (unsigned char const *)arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_bufend_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_bufend_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char *) ((arg1)->bufend);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_unsigned_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_khash_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_khash_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_unsigned_char,
    SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->khash = (unsigned char const *)arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_khash_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_khash_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char *) ((arg1)->khash);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_unsigned_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_vhash_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_vhash_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_unsigned_char,
    SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) SWIG_fail;
    if (arg1) (arg1)->vhash = (unsigned char const *)arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_vhash_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    unsigned char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_vhash_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char *) ((arg1)->vhash);
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_unsigned_char, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagtype_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    int arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_tagtype_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    arg2 = (int)SWIG_As_int(obj1); 
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->tagtype = (KadCtag_type )arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagtype_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_tagtype_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int) ((arg1)->tagtype);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagname_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    char *arg2 ;
    char temp2[256] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_tagname_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    {
        if (!SWIG_AsCharArray(obj1, temp2, 256)) SWIG_fail;
        arg2 = temp2;
    }
    {
        if (arg2) memcpy(arg1->tagname,arg2,256*sizeof(char));
        else memset(arg1->tagname,0,256*sizeof(char));
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagname_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_tagname_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *)(char *) ((arg1)->tagname);
    
    resultobj = SWIG_FromCharArray(result, 256);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagvalue_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    char *arg2 ;
    char temp2[256] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_iter_tagvalue_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    {
        if (!SWIG_AsCharArray(obj1, temp2, 256)) SWIG_fail;
        arg2 = temp2;
    }
    {
        if (arg2) memcpy(arg1->tagvalue,arg2,256*sizeof(char));
        else memset(arg1->tagvalue,0,256*sizeof(char));
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_iter_tagvalue_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_iter_tagvalue_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (char *)(char *) ((arg1)->tagvalue);
    
    resultobj = SWIG_FromCharArray(result, 256);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_KadCtag_iter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_KadCtag_iter")) goto fail;
    result = (KadCtag_iter *)(KadCtag_iter *) calloc(1, sizeof(KadCtag_iter));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_KadCtag_iter, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_KadCtag_iter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_KadCtag_iter",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * KadCtag_iter_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_KadCtag_iter, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_KadCtag_begin(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCdictionary *arg1 = (KadCdictionary *) 0 ;
    KadCtag_iter *arg2 = (KadCtag_iter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:KadCtag_begin",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **)(&arg2),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadCtag_begin(arg1,arg2);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCtag_iter *arg1 = (KadCtag_iter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCtag_next",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadCtag_next(arg1);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCtag_find(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCdictionary *arg1 = (KadCdictionary *) 0 ;
    char *arg2 ;
    KadCtag_iter *arg3 = (KadCtag_iter *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:KadCtag_find",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    if (!SWIG_AsCharPtr(obj1, (char**)&arg2)) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **)(&arg3),SWIGTYPE_p_KadCtag_iter,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (int)KadCtag_find(arg1,arg2,arg3);
    
    resultobj = SWIG_From_int((int)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCdictionary_dump(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCdictionary *arg1 = (KadCdictionary *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCdictionary_dump",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    KadCdictionary_dump(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadCdictionary_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadCdictionary *arg1 = (KadCdictionary *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadCdictionary_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,&arg1,0,SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    KadCdictionary_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_version_t_minor_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadC_version_t *arg1 = (KadC_version_t *) 0 ;
    unsigned char result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_version_t_minor_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadC_version_t,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char)(unsigned char) ((arg1)->minor);
    
    resultobj = SWIG_From_unsigned_SS_char((unsigned char)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_version_t_major_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadC_version_t *arg1 = (KadC_version_t *) 0 ;
    unsigned char result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_version_t_major_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadC_version_t,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char)(unsigned char) ((arg1)->major);
    
    resultobj = SWIG_From_unsigned_SS_char((unsigned char)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_KadC_version_t_patchlevel_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadC_version_t *arg1 = (KadC_version_t *) 0 ;
    unsigned char result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:KadC_version_t_patchlevel_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadC_version_t,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    result = (unsigned char)(unsigned char) ((arg1)->patchlevel);
    
    resultobj = SWIG_From_unsigned_SS_char((unsigned char)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_KadC_version_t(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadC_version_t *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_KadC_version_t")) goto fail;
    result = (KadC_version_t *)(KadC_version_t *) calloc(1, sizeof(KadC_version_t));
    
    resultobj = SWIG_NewPointerObj((void*)(result), SWIGTYPE_p_KadC_version_t, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_KadC_version_t(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    KadC_version_t *arg1 = (KadC_version_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_KadC_version_t",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **)(&arg1),SWIGTYPE_p_KadC_version_t,
    SWIG_POINTER_EXCEPTION | 0)) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * KadC_version_t_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_KadC_version_t, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static int _wrap_KadC_version_set(PyObject *_val) {
    PyErr_SetString(PyExc_TypeError,"Variable KadC_version is read-only.");
    return 1;
}


static PyObject *_wrap_KadC_version_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *)(&KadC_version), SWIGTYPE_p_KadC_version_t, 0);
    return pyobj;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"KadCcontext_s_set", _wrap_KadCcontext_s_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_s_get", _wrap_KadCcontext_s_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_errmsg1_set", _wrap_KadCcontext_errmsg1_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_errmsg1_get", _wrap_KadCcontext_errmsg1_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_errmsg2_set", _wrap_KadCcontext_errmsg2_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_errmsg2_get", _wrap_KadCcontext_errmsg2_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pul_set", _wrap_KadCcontext_pul_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pul_get", _wrap_KadCcontext_pul_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pOKE_set", _wrap_KadCcontext_pOKE_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pOKE_get", _wrap_KadCcontext_pOKE_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pEKE_set", _wrap_KadCcontext_pEKE_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pEKE_get", _wrap_KadCcontext_pEKE_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pRKE_set", _wrap_KadCcontext_pRKE_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_pRKE_get", _wrap_KadCcontext_pRKE_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_inifilename_set", _wrap_KadCcontext_inifilename_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_inifilename_get", _wrap_KadCcontext_inifilename_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_inifile_set", _wrap_KadCcontext_inifile_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_inifile_get", _wrap_KadCcontext_inifile_get, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_wfile_set", _wrap_KadCcontext_wfile_set, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_wfile_get", _wrap_KadCcontext_wfile_get, METH_VARARGS, NULL },
	 { (char *)"new_KadCcontext", _wrap_new_KadCcontext, METH_VARARGS, NULL },
	 { (char *)"delete_KadCcontext", _wrap_delete_KadCcontext, METH_VARARGS, NULL },
	 { (char *)"KadCcontext_swigregister", KadCcontext_swigregister, METH_VARARGS, NULL },
	 { (char *)"KadC_start", _wrap_KadC_start, METH_VARARGS, NULL },
	 { (char *)"KadC_init_network", _wrap_KadC_init_network, METH_VARARGS, NULL },
	 { (char *)"KadC_stop", _wrap_KadC_stop, METH_VARARGS, NULL },
	 { (char *)"KadC_getnknodes", _wrap_KadC_getnknodes, METH_VARARGS, NULL },
	 { (char *)"KadC_getncontacts", _wrap_KadC_getncontacts, METH_VARARGS, NULL },
	 { (char *)"KadC_getfwstatus", _wrap_KadC_getfwstatus, METH_VARARGS, NULL },
	 { (char *)"KadC_getextIP", _wrap_KadC_getextIP, METH_VARARGS, NULL },
	 { (char *)"KadC_getourhashID", _wrap_KadC_getourhashID, METH_VARARGS, NULL },
	 { (char *)"KadC_getourUDPport", _wrap_KadC_getourUDPport, METH_VARARGS, NULL },
	 { (char *)"KadC_getourTCPport", _wrap_KadC_getourTCPport, METH_VARARGS, NULL },
	 { (char *)"nodesinbucket", _wrap_nodesinbucket, METH_VARARGS, NULL },
	 { (char *)"KadC_republish", _wrap_KadC_republish, METH_VARARGS, NULL },
	 { (char *)"KadC_find", _wrap_KadC_find, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagsleft_set", _wrap_KadCtag_iter_tagsleft_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagsleft_get", _wrap_KadCtag_iter_tagsleft_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_pb_set", _wrap_KadCtag_iter_pb_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_pb_get", _wrap_KadCtag_iter_pb_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_bufend_set", _wrap_KadCtag_iter_bufend_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_bufend_get", _wrap_KadCtag_iter_bufend_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_khash_set", _wrap_KadCtag_iter_khash_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_khash_get", _wrap_KadCtag_iter_khash_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_vhash_set", _wrap_KadCtag_iter_vhash_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_vhash_get", _wrap_KadCtag_iter_vhash_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagtype_set", _wrap_KadCtag_iter_tagtype_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagtype_get", _wrap_KadCtag_iter_tagtype_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagname_set", _wrap_KadCtag_iter_tagname_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagname_get", _wrap_KadCtag_iter_tagname_get, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagvalue_set", _wrap_KadCtag_iter_tagvalue_set, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_tagvalue_get", _wrap_KadCtag_iter_tagvalue_get, METH_VARARGS, NULL },
	 { (char *)"new_KadCtag_iter", _wrap_new_KadCtag_iter, METH_VARARGS, NULL },
	 { (char *)"delete_KadCtag_iter", _wrap_delete_KadCtag_iter, METH_VARARGS, NULL },
	 { (char *)"KadCtag_iter_swigregister", KadCtag_iter_swigregister, METH_VARARGS, NULL },
	 { (char *)"KadCtag_begin", _wrap_KadCtag_begin, METH_VARARGS, NULL },
	 { (char *)"KadCtag_next", _wrap_KadCtag_next, METH_VARARGS, NULL },
	 { (char *)"KadCtag_find", _wrap_KadCtag_find, METH_VARARGS, NULL },
	 { (char *)"KadCdictionary_dump", _wrap_KadCdictionary_dump, METH_VARARGS, NULL },
	 { (char *)"KadCdictionary_destroy", _wrap_KadCdictionary_destroy, METH_VARARGS, NULL },
	 { (char *)"KadC_version_t_minor_get", _wrap_KadC_version_t_minor_get, METH_VARARGS, NULL },
	 { (char *)"KadC_version_t_major_get", _wrap_KadC_version_t_major_get, METH_VARARGS, NULL },
	 { (char *)"KadC_version_t_patchlevel_get", _wrap_KadC_version_t_patchlevel_get, METH_VARARGS, NULL },
	 { (char *)"new_KadC_version_t", _wrap_new_KadC_version_t, METH_VARARGS, NULL },
	 { (char *)"delete_KadC_version_t", _wrap_delete_KadC_version_t, METH_VARARGS, NULL },
	 { (char *)"KadC_version_t_swigregister", KadC_version_t_swigregister, METH_VARARGS, NULL },
	 { NULL, NULL, 0, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_unsigned_char[] = {{"_p_unsigned_char", 0, "unsigned char *", 0, 0, 0, 0},{"_p_unsigned_char", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_char[] = {{"_p_char", 0, "char *", 0, 0, 0, 0},{"_p_char", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_KadCtag_iter[] = {{"_p_KadCtag_iter", 0, "struct _KadCtag_iter *|KadCtag_iter *", 0, 0, 0, 0},{"_p_KadCtag_iter", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_int128[] = {{"_p_int128", 0, "int128 *", 0, 0, 0, 0},{"_p_int128", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_KadCcontext[] = {{"_p_KadCcontext", 0, "struct _KadCcontext *|KadCcontext *", 0, 0, 0, 0},{"_p_KadCcontext", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *", 0, 0, 0, 0},{"_p_void", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_KadC_version_t[] = {{"_p_KadC_version_t", 0, "struct _KadC_version_t const *|KadC_version_t const *", 0, 0, 0, 0},{"_p_KadC_version_t", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_unsigned_char, 
_swigt__p_char, 
_swigt__p_KadCtag_iter, 
_swigt__p_int128, 
_swigt__p_KadCcontext, 
_swigt__p_void, 
_swigt__p_KadC_version_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0, 0, 0, 0.0, 0, 0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
    PyDict_SetItemString(d,"KADC_OK", SWIG_From_int((int)KADC_OK));
    PyDict_SetItemString(d,"KADC_START_CANT_OPEN_INI_FILE", SWIG_From_int((int)KADC_START_CANT_OPEN_INI_FILE));
    PyDict_SetItemString(d,"KADC_START_WSASTARTUP_ERROR", SWIG_From_int((int)KADC_START_WSASTARTUP_ERROR));
    PyDict_SetItemString(d,"KADC_START_OVERNET_SECTION_INI_FILE_ERROR", SWIG_From_int((int)KADC_START_OVERNET_SECTION_INI_FILE_ERROR));
    PyDict_SetItemString(d,"KADC_START_EMULEKAD_SECTION_INI_FILE_ERROR", SWIG_From_int((int)KADC_START_EMULEKAD_SECTION_INI_FILE_ERROR));
    PyDict_SetItemString(d,"KADC_START_REVCONNECT_SECTION_INI_FILE_ERROR", SWIG_From_int((int)KADC_START_REVCONNECT_SECTION_INI_FILE_ERROR));
    PyDict_SetItemString(d,"KADC_START_BAD_LOCALNODE_ADDRESS", SWIG_From_int((int)KADC_START_BAD_LOCALNODE_ADDRESS));
    PyDict_SetItemString(d,"KADC_START_NO_MEMORY", SWIG_From_int((int)KADC_START_NO_MEMORY));
    PyDict_SetItemString(d,"KADC_START_UDPIO_FAILED", SWIG_From_int((int)KADC_START_UDPIO_FAILED));
    PyDict_SetItemString(d,"KADC_START_OVERNET_KADENGINE_FAILED", SWIG_From_int((int)KADC_START_OVERNET_KADENGINE_FAILED));
    PyDict_SetItemString(d,"KADC_START_EMULEKAD_KADENGINE_FAILED", SWIG_From_int((int)KADC_START_EMULEKAD_KADENGINE_FAILED));
    PyDict_SetItemString(d,"KADC_START_REVCONNECT_KADENGINE_FAILED", SWIG_From_int((int)KADC_START_REVCONNECT_KADENGINE_FAILED));
    PyDict_SetItemString(d,"KADC_START_RTP_FAILED", SWIG_From_int((int)KADC_START_RTP_FAILED));
    PyDict_SetItemString(d,"KADC_NEVER_STARTED", SWIG_From_int((int)KADC_NEVER_STARTED));
    PyDict_SetItemString(d,"KADC_STOP_OVERNETINIFILEUPDATE_FAILED", SWIG_From_int((int)KADC_STOP_OVERNETINIFILEUPDATE_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_OVERNET_FAILED", SWIG_From_int((int)KADC_STOP_OVERNET_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_EMULEKAD_FAILED", SWIG_From_int((int)KADC_STOP_EMULEKAD_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_REVCONNECT_FAILED", SWIG_From_int((int)KADC_STOP_REVCONNECT_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_RTP_FAILED", SWIG_From_int((int)KADC_STOP_RTP_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_UDPIO_FAILED", SWIG_From_int((int)KADC_STOP_UDPIO_FAILED));
    PyDict_SetItemString(d,"KADC_STOP_CANT_CREATE_NEW_INI_FILE", SWIG_From_int((int)KADC_STOP_CANT_CREATE_NEW_INI_FILE));
    PyDict_SetItemString(d,"KADCTAG_INVALID", SWIG_From_int((int)KADCTAG_INVALID));
    PyDict_SetItemString(d,"KADCTAG_NOTFOUND", SWIG_From_int((int)KADCTAG_NOTFOUND));
    PyDict_SetItemString(d,"KADCTAG_HASH", SWIG_From_int((int)KADCTAG_HASH));
    PyDict_SetItemString(d,"KADCTAG_STRING", SWIG_From_int((int)KADCTAG_STRING));
    PyDict_SetItemString(d,"KADCTAG_ULONGINT", SWIG_From_int((int)KADCTAG_ULONGINT));
    PyDict_SetItemString(d,(char*)"cvar", SWIG_globals);
    SWIG_addvarlink(SWIG_globals,(char*)"KadC_version",_wrap_KadC_version_get, _wrap_KadC_version_set);
}

